[package]
name = "lique_linter"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.5.0"
lique_core = { path = "../lique_core" }
oq3_semantics = { workspace = true }
oq3_source_file = { workspace = true }

