[workspace]
members = ["lique_core", "lique_linter", "lique_ls"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.93"
oq3_semantics = "0.7.0"
oq3_source_file = "0.7.0"
serde = { version = "1.0.214", features = ["derive"] }
