[package]
name = "lique_core"
version = "0.1.0"
edition = "2021"

[dependencies]
oq3_semantics = { workspace = true }
oq3_source_file = { workspace = true }
oq3_syntax = "0.7.0"
serde = { workspace = true }
thiserror = "2.0.3"
